name: Secretlint via Node.js only on changed files
on: [push, pull_request]

# secretlint + git diff on Pull Request
# https://github.com/secretlint/secretlint

jobs:
  run-secretlint:
    name: "Secretlint only on changed files"
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v5
      - uses: technote-space/get-diff-action@v6
      - name: setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install
        run: npm install
      - name: Lint with Secretlint
        run: npx --no-install secretlint ${{ env.GIT_DIFF_FILTERED }}
        if: env.GIT_DIFF && !env.MATCHED_FILES
