name: Secretlint
on: [push, pull_request]
permissions:
  contents: read
jobs:
  secretlint:
    name: "Secretlint"
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install
        run: npm install
      - name: Lint with Secretlint
        run: npx secretlint "**/*"
